[14.0][MIG] purchase_order_type_advanced
solvosci/slv-purchase pull request #21
Opened 2022-08-31 07:55 UTC by ChristianSantamaria

Standard migration to v14
--
`type `field in v13 is renamed in v14 to `move_type` and
`.with_context(force_company=...)` became `.with_company(...)`

2022-08-31 10:31 UTC, ChristianSantamaria commented
@dalonsod, could you check it un Test environment? Thanks!

2022-08-31 16:11 UTC, dalonsod requested changes
See comment.
When testing, I've found an error, but not sure if this addon is involved:

- Created a second purchase order sequence for VGO Purchases.
- Created a second warehouse "VG".
- Created a new purchases journal TEMP.
- Created a new purchase order type for VGO purchases... with the above sequence, the incoming operation type for VG as default and default journal, the TEMP one.
- When confirmed a VGO purchase and validated the picking, product were placed in VGO stock location (OK).
- But an error is raised when I've tried to validate that the created invoiced assigned to the proper journal:

![imagen](https://user-images.githubusercontent.com/12749832/187726606-482a2595-0208-4679-9451-df2688e0523c.png)

could you check?

cc @lmiguens-solvos

2022-08-31 16:11 UTC, dalonsod commented on purchase_order_type_advanced/__manifest__.py
> +    "version": "14.0.1.0.2",
Reset version to `14.0.1.0.0`

2022-10-04 15:44 UTC, dalonsod commented on purchase_order_type_advanced/models/purchase_order.py
> +        res["context"].update(ctx)
In v14 this `res["context"]` seems to be a string, not a dictionary, so this `update()` fails.
Tested in AR Test Environment, clicking in purchase invoices button, this error is raised:

```
  File "/home/odoo/odoo-test/erp-ariveira/src/slv-purchase/purchase_order_type_advanced/models/purchase_order.py", line 24, in action_view_invoice
    res["context"].update(ctx)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo-test/erp-ariveira/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-test/erp-ariveira/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'str' object has no attribute 'update'
```

2022-10-11 16:32 UTC, dalonsod commented on purchase_order_type_advanced/models/purchase_order.py
> +        res["context"].update(ctx)
Solved!

2022-10-11 16:33 UTC, dalonsod commented
> * But an error is raised when I've tried to validate that the created invoiced assigned to the proper journal

Solved by the last commit

2022-10-11 16:33 UTC, dalonsod commented
@ChristianSantamaria please update in both customers Test environments, so we'll test it again. Thanks!

2022-10-27 16:58 UTC, dalonsod commented
Last commit is still untested, so I've move this PR back to draft

2022-11-09 14:53 UTC, dalonsod commented
Already validated by at least one customer, let's merge it...

2022-11-09 14:53 UTC, merged