[14.0][ADD] stock_warehouse_analytic_purchase
solvosci/slv-purchase pull request #53
Opened 2024-10-01 11:09 UTC by ChristianSantamaria

Adds to the analytical fields and analytical tags of the lines that are automatically calculated

2024-10-01 17:53 UTC, dalonsod requested changes
Not sure if this PR was ready to be reviewed, if not I'm sorry... anyway, I've made some comments to be checked

2024-10-01 17:53 UTC, dalonsod commented on stock_warehouse_analytic_purchase/models/purchase_order_line.py
> +        for record in self.filtered(lambda x: x.order_id.picking_type_id.warehouse_id.account_analytic_id):
According to original method definition (https://github.com/odoo/odoo/blob/f2765d2cab5671a010404c36842bf1b4c4d6350b/addons/purchase/models/purchase.py#L1013) those special purchase lines (section and notes, not regular lines) should be ignored in the process

2024-10-01 17:53 UTC, dalonsod commented on stock_warehouse_analytic_purchase/models/purchase_order_line.py
> +    @api.depends('order_id.picking_type_id.warehouse_id.account_analytic_id', 'order_id.picking_type_id.warehouse_id.account_analytic_tag_ids')
For `tag_ids` there's a separated compute method, please check

2024-10-01 17:53 UTC, dalonsod commented on stock_warehouse_analytic_purchase/models/purchase_order_line.py
> +from odoo import _, models, api
Remove unused import:
```suggestion
from odoo import models, api
```

2024-10-01 17:53 UTC, dalonsod commented on stock_warehouse_analytic_purchase/readme/DESCRIPTION.rst
> +Adds to the analytical fields and analytical tags of the lines that are automatically calculated
Please rewrite description and make it more detailed (this definition doesn't refer to warehouses, and does not indicate that this new definition has higher priority and default analytic rules)

2024-10-02 09:36 UTC, dalonsod commented
OK, I have some performance doubts with the current implementation:

- When `account_analytic_id` and/or `account_analytic_tag_ids` are changed in stock.warehouse record, every affected purchase order line (POL) is automatically changed?
- With `stock_warehouse_analytic` already installed and configured for a warehouse, when we install this addon, account and tag fields for POL are updated?

I'm worried about installing (and later configuring) this in a Production environment with a lot of POLs.

Please check both questions, and I'll decide if we move `@api.depends` from current field to simply `order_id.picking_type_id`, which could be less aggressive.

2024-10-02 12:23 UTC, ChristianSantamaria commented
`When account_analytic_id and/or account_analytic_tag_ids are changed in stock.warehouse record, every affected purchase order line (POL) is automatically changed?`
Yes, when you modify an account or label, the fields of the lines are modified.

`With stock_warehouse_analytic already installed and configured for a warehouse, when we install this addon, account and tag fields for POL are updated?`
No, when installing the addon they are not recalculated.

2024-10-02 12:36 UTC, dalonsod commented
OK, then we'll make the following changes (temporary in a separate commit):

- Move `@api.depends` to only `order_id.picking_type_id`.
- Check that a later change in warehouse doesn't affect existing PO lines.
- Check that functionality still works (for new POLs analytic is proper applied, and if Picking Operation Type for PO is changed, analytic is changed to).

2024-10-04 06:07 UTC, ChristianSantamaria commented
`Check that a later change in warehouse doesn't affect existing PO lines.`
Checked not affect

`Check that functionality still works (for new POLs analytic is proper applied, and if Picking Operation Type for PO is changed, analytic is changed to).`
Still work

2024-10-09 17:11 UTC, dalonsod approved these changes
Approved by customer :+1:

2024-10-09 17:11 UTC, merged