[17.0][MIG] purchase_order_partner_ref_mandatory
solvosci/slv-purchase pull request #55
Opened 2024-10-03 07:33 UTC by Anxo82

Standard migration

2024-10-05 09:25 UTC, dalonsod requested changes
See comments (some things should be probably wrong in `v15` implementation indeed). And please make a rebase with `17.0`, so already merged content is available.

2024-10-05 09:25 UTC, dalonsod commented on purchase_order_partner_ref_mandatory/views/purchase_order_views.xml
> +                <attribute name="invisible">True</attribute>
Column is still available and can be selected:

![imagen](https://github.com/user-attachments/assets/5429b2fd-4049-425c-bf19-b320134e9e3b)

but to has no content (this is because `invisible` attribute). In order to make column actually invisible, try `column_invisible`.

2024-10-05 09:25 UTC, dalonsod commented on purchase_order_partner_ref_mandatory/views/purchase_order_views.xml
> +                    <span name="span_partner_ref"><t t-esc="record.partner_ref.value"/></span>
`t-esc` actually works. I'm not sure, but for kanban views, has any substitute like `t-out` (look at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0)?

2024-10-05 09:25 UTC, dalonsod commented on purchase_order_partner_ref_mandatory/views/purchase_order_views.xml
> +                <attribute name="invisible">True</attribute>
The same as above

2024-10-08 17:19 UTC, dalonsod approved these changes
Tested :+1:  make two minor changes and I'll merge it:
- Later changes in views are placed in the wrong commit (they should be placed in Migration commit, not in README update one).
- Add yourself as contributor, because this migration contains some fixes

2024-10-09 14:55 UTC, Anxo82 commented
@dalonsod I've could add changes to migration commit, but no delete to readme commit.
Thanks

2024-10-09 15:31 UTC, dalonsod commented
OK, I'll try

2024-10-09 15:39 UTC, dalonsod commented
Done with the following commands:

```
cd purchase_order_partner_ref_mandatory/views/
git checkout b7718f1029e6486aced31dba1ea9c3ac3ef92962 purchase_order_views.xml
```

With these commands, affected file is restore to previous commit (`b7718f1029e6486aced31dba1ea9c3ac3ef92962`) state. Then, commited and squashed it.

Ready to be merged!

2024-10-09 15:39 UTC, merged